import type { CatalogSourceConfig } from "./types.ts";

export const catalogSourceRegistry: CatalogSourceConfig[] = [
  {
    code: "seven_eleven_jp",
    brandName: "セブン-イレブン",
    baseUrl: "https://www.sej.co.jp",
    rootUrl: "https://www.sej.co.jp/products/",
    strategy: "catalog_tree",
    isEnabled: true,
    supportsFullNutrition: true,
    categoryHints: ["onigiri", "bento", "men", "sandwich"],
    detailUrlPatterns: [/\/products\/a\/item\/\d+(?:\/[a-z0-9_-]+)?\/?$/i],
    categoryUrlPatterns: [
      /\/products\/a\/[a-z0-9_-]+(?:\/[a-z0-9_-]+)?\/$/i,
      /\/products\/a\/cat\/\d+\/(?:[a-z0-9_-]+\/)?$/i,
    ],
    nutritionMarkers: ["栄養成分", "熱量", "たんぱく質", "脂質", "炭水化物", "食塩相当量"],
  },
  {
    code: "familymart_jp",
    brandName: "ファミリーマート",
    baseUrl: "https://www.family.co.jp",
    rootUrl: "https://www.family.co.jp/goods.html",
    strategy: "catalog_tree",
    isEnabled: true,
    supportsFullNutrition: true,
    categoryHints: ["omusubi", "obento", "sandwich", "noodle", "pasta", "sidedishes"],
    detailUrlPatterns: [/\/goods\/[a-z0-9_-]+\/\d+\.html$/i],
    categoryUrlPatterns: [/\/goods\/[a-z0-9_-]+\.html$/i],
    nutritionMarkers: ["栄養成分", "熱量", "たんぱく質", "脂質", "炭水化物", "食塩相当量", "アレルゲン"],
  },
  {
    code: "lawson_jp",
    brandName: "ローソン",
    baseUrl: "https://www.lawson.co.jp",
    rootUrl: "https://www.lawson.co.jp/recommend/original/",
    strategy: "catalog_tree",
    isEnabled: true,
    supportsFullNutrition: true,
    categoryHints: ["rice", "bento", "sandwich", "noodle", "salad", "select"],
    detailUrlPatterns: [/\/recommend\/original\/detail\/\d{7}_\d{4}\.html$/i],
    categoryUrlPatterns: [/\/recommend\/original\/(?!detail\/)(?:[a-z0-9_-]+\/)*(?:index\.html)?$/i],
    nutritionMarkers: ["nutritionFacts_table", "栄養成分", "アレルギー情報"],
  },
  {
    code: "lawson_store100_jp",
    brandName: "ローソンストア100",
    baseUrl: "https://store100.lawson.co.jp",
    rootUrl: "https://store100.lawson.co.jp/product/",
    strategy: "partial_nutrition_catalog",
    isEnabled: true,
    supportsFullNutrition: false,
    detailUrlPatterns: [/\/product\/[a-z0-9_-]+\/detail\/\d{7}_\d{4}\.html$/i],
    categoryUrlPatterns: [/\/product\/[a-z0-9_-]+\/$/i, /\/product\/[a-z0-9_-]+\/category\/\d+_\d+\.html$/i],
    nutritionMarkers: [],
    notes: ["detail 3件を手監査したが full nutrition 欄は未確認。price / region / image までを partial source として扱う"],
  },
  {
    code: "natural_lawson_jp",
    brandName: "ナチュラルローソン",
    baseUrl: "https://natural.lawson.co.jp",
    rootUrl: "https://natural.lawson.co.jp/recommend/",
    strategy: "catalog_tree_shared_parent",
    parentSourceCode: "lawson_jp",
    isEnabled: true,
    supportsFullNutrition: true,
    detailUrlPatterns: [/\/(?:sp\/)?recommend\/commodity\/detail\/\d{7}_\d{4}\.html$/i],
    categoryUrlPatterns: [
      /\/(?:sp\/)?recommend\/commodity\/(?:index\.html)?$/i,
      /\/(?:sp\/)?recommend\/commodity\/\d+\/\d+_\d+\.html$/i,
    ],
    nutritionMarkers: ["熱量", "たんぱく質", "脂質", "炭水化物", "食塩相当量", "アレルギー情報"],
    notes: ["detail は Lawson 系共通 parser を流用し、discovery だけ Natural Lawson 向けに分ける"],
  },
  {
    code: "ministop_jp",
    brandName: "ミニストップ",
    baseUrl: "https://www.ministop.co.jp",
    rootUrl: "https://www.ministop.co.jp/syohin/",
    strategy: "catalog_tree",
    isEnabled: true,
    supportsFullNutrition: true,
    detailUrlPatterns: [/\/syohin\/products\/detail\d{6,}\.html$/i],
    categoryUrlPatterns: [/\/syohin\/[a-z0-9_-]+(?:\/[a-z0-9_-]+)?\/$/i],
    nutritionMarkers: ["栄養成分情報", "アレルゲン情報", "エネルギー", "たんぱく質", "脂質", "炭水化物"],
    notes: [
      "有効な detail URL は `detail050627.html` のような 6 桁以上のみ。`detail1.html` 系は Firecrawl が inline lineup から生成する偽 URL なので除外する",
      "`onigiri` / `obento` の旧 public category は 403 のため、現状は `tennai-tezukuri` fallback と専用 inline parser が必要",
    ],
  },
  {
    code: "daily_yamazaki_jp",
    brandName: "デイリーヤマザキ",
    baseUrl: "https://www.daily-yamazaki.jp",
    rootUrl: "https://www.daily-yamazaki.jp/new/",
    strategy: "partial_nutrition_catalog",
    isEnabled: true,
    supportsFullNutrition: false,
    categoryUrlPatterns: [/\/new\/(?:page\/\d+\/)?$/i],
    nutritionMarkers: ["熱量", "アレルゲン"],
    notes: ["`new/` 本体に商品 modal HTML が埋め込まれている。現時点では熱量とアレルゲンのみ確認"],
  },
  {
    code: "seicomart_jp",
    brandName: "セイコーマート",
    baseUrl: "https://www.seicomart.co.jp",
    rootUrl: "https://www.seicomart.co.jp/instore/new.html",
    strategy: "news_feed_catalog",
    isEnabled: false,
    supportsFullNutrition: false,
    nutritionMarkers: ["栄養成分", "熱量", "たんぱく質", "脂質", "炭水化物", "食塩相当量"],
    notes: ["週次 single page は確認できたが full nutrition source は未確認。追加監査まで disabled"],
  },
  {
    code: "sakura_mikura_jp",
    brandName: "さくらみくら",
    baseUrl: "https://www.sakura-mikura.jp",
    rootUrl: "https://www.sakura-mikura.jp/",
    strategy: "weak_catalog",
    isEnabled: false,
    supportsFullNutrition: false,
    notes: ["root は確認済みだが商品 detail / nutrition tree は未確認"],
  },
  {
    code: "poplar_group_jp",
    brandName: "ポプラグループ",
    baseUrl: "https://www.poplar-cvs.co.jp",
    rootUrl: "https://www.poplar-cvs.co.jp/",
    strategy: "weak_catalog",
    isEnabled: false,
    supportsFullNutrition: false,
    notes: ["campaign / IR 中心。商品 SKU tree と栄養 detail が未確認"],
  },
  {
    code: "cisca_jp",
    brandName: "cisca",
    baseUrl: "https://www.cisca.jp",
    rootUrl: "https://www.cisca.jp/",
    strategy: "weak_catalog",
    isEnabled: false,
    supportsFullNutrition: false,
    notes: ["一般公開の栄養付き商品カタログは未確認"],
  },
  {
    code: "newdays_jp",
    brandName: "JR東日本クロスステーション / NewDays",
    baseUrl: "https://retail.jr-cross.co.jp",
    rootUrl: "https://retail.jr-cross.co.jp/newdays/product/",
    strategy: "partial_nutrition_catalog",
    isEnabled: true,
    supportsFullNutrition: false,
    detailUrlPatterns: [/\/newdays\/menu\/detail\/\d+\.html$/i],
    categoryUrlPatterns: [/\/newdays\/product\/$/i],
    nutritionMarkers: [],
    notes: ["root JS が `data_allproductlist.json` を fetch する。JSON から一覧は取れるが detail に full nutrition 欄は未確認"],
  },
  {
    code: "shikoku_kiosk_jp",
    brandName: "四国キヨスク",
    baseUrl: "https://www.s-kiosk.jp",
    rootUrl: "https://www.s-kiosk.jp/",
    strategy: "weak_catalog",
    isEnabled: false,
    supportsFullNutrition: false,
    notes: ["独立した商品栄養カタログを未確認。親ブランド共有の可能性がある"],
  },
  {
    code: "orebo_jp",
    brandName: "大津屋 / オレボ",
    baseUrl: "https://www.orebo.jp",
    rootUrl: "https://www.orebo.jp/news/",
    strategy: "news_feed_catalog",
    isEnabled: false,
    supportsFullNutrition: false,
    notes: ["news article 中心で full nutrition source を未確認。追加監査まで disabled"],
  },
];

export function getCatalogSourceConfig(sourceCode: string) {
  return catalogSourceRegistry.find((source) => source.code === sourceCode) ?? null;
}
