// ハンズオン中で使う固定値
// Canonical: docs/design/family/09-onboarding-handson-tour/14-mocks-i18n.md §5.1

export const HANDSON_TOUR_CONSTANTS = {
  // 各ステップの自動進行タイマー (ms)
  STEP1_INTRO_AUTO_MS: 2500,
  STEP1_CAMERA_AUTO_MS: 2000,
  STEP1_ANALYZING_DURATION_MS: 1500,
  STEP1_RESULT_TO_SPOTLIGHT_MS: 500,

  STEP2_INTRO_AUTO_MS: 2500,
  STEP2_LOADING_DURATION_MS: 2000,

  STEP3_INTRO_AUTO_MS: 2000,

  STEP4_SAVING_DELAY_MS: 100,
  STEP4_BUTTON_ACTIVATION_MS: 5000,

  STEP5_TOAST_DURATION_MS: 4000,

  // エラー連続失敗閾値
  ERROR_CONSECUTIVE_THRESHOLD: 3,

  // タイムアウト
  STATUS_API_TIMEOUT_MS: 5000,
  COMPLETE_API_TIMEOUT_MS: 10000,

  // アニメーション
  OVERLAY_FADE_IN_MS: 200,
  OVERLAY_FADE_OUT_MS: 200,
  SPOTLIGHT_MOVE_MS: 250,
  BUBBLE_FADE_IN_MS: 150,
  BUBBLE_FADE_DELAY_MS: 100,

  // 紙吹雪
  CONFETTI_PARTICLE_COUNT: 300,
  CONFETTI_DURATION_MS: 3000,

  // バッジ
  BADGE_GLOW_DURATION_MS: 1000,
} as const;

export type HandsonTourConstantsKey = keyof typeof HANDSON_TOUR_CONSTANTS;
